package layout

import (
	"louis14/pkg/css"
	"louis14/pkg/html"
)

// LayoutInputNode is the layout tree node, wrapping a DOM node or an
// anonymous box. Layout algorithms operate on these, never on *html.Node
// directly. The layout tree is built from the DOM by LayoutTreeBuilder
// before layout begins.
//
// Mirrors Blink's LayoutInputNode / LayoutObject.
type LayoutInputNode struct {
	// DOMNode is the underlying DOM node, or nil for anonymous boxes.
	DOMNode *html.Node

	// style is the computed style for this node.
	// For anonymous boxes, this is a synthesized style inheriting from the parent.
	style *css.Style

	// children are the layout children (pre-filtered, may include anonymous wrappers).
	children []*LayoutInputNode

	// isAnonymous is true for generated anonymous boxes (CSS 2.1 §9.2.1.1).
	isAnonymous bool

	// isContinuation is true for nodes generated by CSS 2.1 §9.2.1.1
	// block-in-inline splitting (inline element split around a block child).
	// The anonymous block wrapper should inherit the continuation's background.
	isContinuation bool

	// isFirstContinuation / isLastContinuation distinguish the first and last
	// fragments of a split inline element. Only meaningful when isContinuation
	// is true. For a non-split inline element both are implicitly true.
	//
	// CSS 2.1 §9.2.1.1: inline-start margin/border/padding applies only before
	// the first fragment; inline-end margin/border/padding applies only after
	// the last fragment.
	isFirstContinuation bool
	isLastContinuation  bool

	// Box is the layout Box produced for this node by fragmentToBox.
	// Nil until layout is complete. Set only for element nodes (not text, not anonymous).
	// Provides the LayoutInputNode→Box direction of the bidirectional link used
	// by BuildPaintTree for DOM-ordered traversal.
	Box *Box

	// MarkerStyle is the computed ::marker pseudo-element style for list items.
	// Set during layout tree building when display: list-item has matching ::marker rules.
	MarkerStyle *css.Style

	// MarkerContent is the resolved text content from ::marker { content: ... }.
	// Set during layout tree building when counter() values can be resolved.
	MarkerContent string

	// FirstLineStyle is the computed ::first-line pseudo-element style.
	// Set during layout tree building for block containers with matching
	// ::first-line rules. Applied to inline items on the first formatted line.
	FirstLineStyle *css.Style

	// DOMIndex is a pre-order index in the DOM tree, used to ensure correct
	// paint ordering when out-of-flow children propagate to ancestor boxes.
	DOMIndex int

	// groupedChildrenCache caches the result of groupInlineChildrenForMulticol
	// so that repeated Layout() calls on the same multicol node return the same
	// anonymous block pointer identities. Without this cache, each invocation
	// creates fresh anonymous wrappers, causing break-token node-pointer
	// comparisons to fail when resuming a column in a later outer column.
	groupedChildrenCache []*LayoutInputNode

	// contentNodeCache caches the anonymous wrapper that
	// MulticolLayoutAlgorithm constructs around the multicol's children.
	// Stable across Layout() calls so the MulticolPartWalker's
	// child.Node == multicolContainer dispatch survives outer-fragmentainer
	// resumes. Without this cache, each Layout() call allocates a fresh anon
	// wrapper; outer column 1 emits break tokens referencing the col-1
	// pointer, but outer column 2 builds the walker with the col-2 pointer,
	// and the equality check fails — every column-content resume then
	// mis-dispatches as a spanner. Mirrors the LayoutObject pointer
	// stability that Blink's column-box assumes.
	contentNodeCache *LayoutInputNode
}

// Style returns the computed style for this node.
func (n *LayoutInputNode) Style() *css.Style {
	return n.style
}

// Children returns the layout children.
func (n *LayoutInputNode) Children() []*LayoutInputNode {
	return n.children
}

// IsAnonymous returns true for generated anonymous boxes.
func (n *LayoutInputNode) IsAnonymous() bool {
	return n.isAnonymous
}

// IsFirstFragment returns true if this node is the first visual fragment of
// its inline element. True for regular (non-split) inlines and for the first
// continuation of a block-in-inline split.
func (n *LayoutInputNode) IsFirstFragment() bool {
	return !n.isContinuation || n.isFirstContinuation
}

// IsLastFragment returns true if this node is the last visual fragment of
// its inline element. True for regular (non-split) inlines and for the last
// continuation of a block-in-inline split.
func (n *LayoutInputNode) IsLastFragment() bool {
	return !n.isContinuation || n.isLastContinuation
}

// IsElement returns true for element-like nodes (not text, not anonymous).
func (n *LayoutInputNode) IsElement() bool {
	return n.DOMNode != nil && n.DOMNode.Type == html.ElementNode
}

// IsText returns true for text nodes.
func (n *LayoutInputNode) IsText() bool {
	return n.DOMNode != nil && n.DOMNode.Type == html.TextNode
}

// TagName returns the element's tag name, or "" for text/anonymous nodes.
func (n *LayoutInputNode) TagName() string {
	if n.DOMNode != nil {
		return n.DOMNode.TagName
	}
	return ""
}

// TextContent returns the text content for text nodes, or "".
func (n *LayoutInputNode) TextContent() string {
	if n.DOMNode != nil {
		return n.DOMNode.Text
	}
	return ""
}

// IsListItem returns true when this node establishes a list-item formatting
// context (display:list-item). Mirrors Blink's BlockNode::IsListItem().
func (n *LayoutInputNode) IsListItem() bool {
	return n.style != nil && n.style.GetDisplay() == css.DisplayListItem
}

// ListMarkerBlockNodeIfListItem returns a LayoutInputNode for the ::marker
// pseudo-element if this is a list-item, or nil otherwise.
//
// In Blink, ListMarkerBlockNodeIfListItem returns a BlockNode wrapping the
// ::marker LayoutBox. In Louis14, markers are currently drawn at paint time
// (pkg/render/render.go drawListMarker); there is no layout-time marker node.
// Returning nil here makes the UnpositionedListMarker protocol a no-op, which
// is the correct behaviour for the Track C +0 port: the paint-time path
// remains the sole marker-drawing path until a future cleanup phase decides
// which wins. Mirrors Blink cla.cc:240 constructor guard.
func (n *LayoutInputNode) ListMarkerBlockNodeIfListItem() *LayoutInputNode {
	return nil
}

// ListMarkerOccupiesWholeLine returns true when list-style-position:inside
// causes the marker to occupy the first line of content (inside marker).
// Mirrors Blink's BlockNode::ListMarkerOccupiesWholeLine().
// Always false for outside markers (the common case).
func (n *LayoutInputNode) ListMarkerOccupiesWholeLine() bool {
	if n.style == nil {
		return false
	}
	return n.style.GetListStylePosition() == "inside"
}
