package layout

import (
	"louis14/pkg/css"
	"louis14/pkg/html"
)

// LayoutInputNode is louis14's single layout-tree node type. It wraps a
// DOM node or an anonymous box; layout algorithms operate on these, never
// on *html.Node directly. The layout tree is built from the DOM by
// LayoutTreeBuilder before layout begins.
//
// Architecture note — deliberate two-tier collapse vs Blink's three-tier
// model. Blink splits this role across LayoutInputNode (input-side cursor),
// LayoutObject (abstract base of the layout tree), and LayoutBox (concrete
// persistent box with caches and a fragment list). The split exists for
// C++ value-vs-pointer ergonomics, Oilpan GC integration, and a deep
// inheritance hierarchy — none of which apply in Go, where pointer
// semantics + GC + interfaces collapse the model into one tier without
// loss of expressiveness.
//
// Consequences for the rest of the codebase:
//   - *LayoutInputNode pointers are persistent across Layout() calls and
//     serve as the stable identity that Blink uses *LayoutBox for. The
//     groupedChildrenCache and contentNodeCache fields exist specifically
//     to preserve that stability inside the multicol algorithm.
//   - Where Blink keys maps by *LayoutBox (e.g., FragmentedOofData's
//     multicols-with-pending-OOFs map, OrthogonalLayoutCache), louis14
//     keys them by *LayoutInputNode. Same identity, one fewer indirection.
//   - The downstream paint-tree type is Box (types.go); the Box pointer
//     on this struct is the layout-tree → paint-tree link.
type LayoutInputNode struct {
	// DOMNode is the underlying DOM node, or nil for anonymous boxes.
	DOMNode *html.Node

	// style is the computed style for this node.
	// For anonymous boxes, this is a synthesized style inheriting from the parent.
	style *css.Style

	// children are the layout children (pre-filtered, may include anonymous wrappers).
	children []*LayoutInputNode

	// isAnonymous is true for generated anonymous boxes (CSS 2.1 §9.2.1.1).
	isAnonymous bool

	// isContinuation is true for nodes generated by CSS 2.1 §9.2.1.1
	// block-in-inline splitting (inline element split around a block child).
	// The anonymous block wrapper should inherit the continuation's background.
	isContinuation bool

	// isFirstContinuation / isLastContinuation distinguish the first and last
	// fragments of a split inline element. Only meaningful when isContinuation
	// is true. For a non-split inline element both are implicitly true.
	//
	// CSS 2.1 §9.2.1.1: inline-start margin/border/padding applies only before
	// the first fragment; inline-end margin/border/padding applies only after
	// the last fragment.
	isFirstContinuation bool
	isLastContinuation  bool

	// Box is the layout Box produced for this node by fragmentToBox.
	// Nil until layout is complete. Set only for element nodes (not text, not anonymous).
	// Provides the LayoutInputNode→Box direction of the bidirectional link used
	// by BuildPaintTree for DOM-ordered traversal.
	Box *Box

	// markerNode is the ::marker pseudo-element LayoutInputNode for a
	// list-item node. Set during layout tree building by
	// createMarkerPseudoElement for BOTH inside and outside markers; mirrors
	// Blink's pseudo-element child reached via
	// LayoutListItem::Marker()/PseudoElementLayoutObject(kPseudoIdMarker).
	// For an inside marker the same node is also prepended into the list
	// item's inline children; for an outside marker it is reachable only
	// through ListMarkerBlockNodeIfListItem (the carry/claim protocol owns
	// its placement). Nil when no marker is generated.
	markerNode *LayoutInputNode

	// MarkerCategory is the ListStyleCategory of this ::marker node's
	// originating list item (CategoryNone for image markers). Meaningful only
	// on a marker node. Mirrors the category dispatch in Blink ListMarker.
	MarkerCategory ListStyleCategory

	// MarkerIsOutside is true when this ::marker node's originating list item
	// has list-style-position: outside (the default). Read off the
	// originating item, never off the ::marker (CSS Pseudo-4 §4.4).
	// Meaningful only on a marker node.
	MarkerIsOutside bool

	// MarkerTextTyp is the MarkerTextType of this ::marker node's resolved
	// text (MarkerNotText for image / content:none markers). Meaningful only
	// on a marker node. Mirrors Blink ListMarker::marker_text_type_.
	MarkerTextTyp MarkerTextType

	// isMarkerNode is true for the synthetic ::marker pseudo-element node.
	// Lets the ::first-letter walk and inline collection identify and skip
	// the marker box (docs/plan-css-pseudo.md Phases 3-4).
	isMarkerNode bool

	// markerContentIsGenerated is true when this ::marker node's text came
	// from an author-specified `::marker { content }` (generated content)
	// rather than from the resolved list-style-type. Meaningful only on a
	// marker node. Used during Phase 2/3/4 transition to feed the legacy
	// paint path with exactly its historical inputs.
	markerContentIsGenerated bool

	// FirstLineStyle is the computed ::first-line pseudo-element style.
	// Set during layout tree building for block containers with matching
	// ::first-line rules. Applied to inline items on the first formatted line.
	FirstLineStyle *css.Style

	// DOMIndex is a pre-order index in the DOM tree, used to ensure correct
	// paint ordering when out-of-flow children propagate to ancestor boxes.
	DOMIndex int

	// SVGRoot is non-nil for an inline <svg> element after layout. It owns
	// the SVG coordinate system (viewBox / preserveAspectRatio /
	// localToBorderBoxTransform) and the SVG layout subtree below the
	// <svg> box. Set by SVGRootAlgorithm.Layout(). Mirrors how Blink
	// painters reach the SVG root via LayoutSVGRoot from the layout box
	// (To<LayoutSVGRoot>(layout_box_)) — louis14's collapsed layout-tree
	// model puts that pointer on the LayoutInputNode that produces the
	// <svg> box. Typed as `any` here to avoid an import cycle
	// (pkg/layout/svg imports pkg/geometry; pkg/layout imports
	// pkg/layout/svg). Callers in pkg/render cast to *svg.SVGRoot.
	SVGRoot any

	// groupedChildrenCache caches the result of groupInlineChildrenForMulticol
	// so that repeated Layout() calls on the same multicol node return the same
	// anonymous block pointer identities. Without this cache, each invocation
	// creates fresh anonymous wrappers, causing break-token node-pointer
	// comparisons to fail when resuming a column in a later outer column.
	groupedChildrenCache []*LayoutInputNode

	// contentNodeCache caches the anonymous wrapper that
	// MulticolLayoutAlgorithm constructs around the multicol's children.
	// Stable across Layout() calls so the MulticolPartWalker's
	// child.Node == multicolContainer dispatch survives outer-fragmentainer
	// resumes. Without this cache, each Layout() call allocates a fresh anon
	// wrapper; outer column 1 emits break tokens referencing the col-1
	// pointer, but outer column 2 builds the walker with the col-2 pointer,
	// and the equality check fails — every column-content resume then
	// mis-dispatches as a spanner. Mirrors the LayoutObject pointer
	// stability that Blink's column-box assumes.
	contentNodeCache *LayoutInputNode
}

// Style returns the computed style for this node.
func (n *LayoutInputNode) Style() *css.Style {
	return n.style
}

// Children returns the layout children.
func (n *LayoutInputNode) Children() []*LayoutInputNode {
	return n.children
}

// IsAnonymous returns true for generated anonymous boxes.
func (n *LayoutInputNode) IsAnonymous() bool {
	return n.isAnonymous
}

// IsFirstFragment returns true if this node is the first visual fragment of
// its inline element. True for regular (non-split) inlines and for the first
// continuation of a block-in-inline split.
func (n *LayoutInputNode) IsFirstFragment() bool {
	return !n.isContinuation || n.isFirstContinuation
}

// IsLastFragment returns true if this node is the last visual fragment of
// its inline element. True for regular (non-split) inlines and for the last
// continuation of a block-in-inline split.
func (n *LayoutInputNode) IsLastFragment() bool {
	return !n.isContinuation || n.isLastContinuation
}

// IsElement returns true for element-like nodes (not text, not anonymous).
func (n *LayoutInputNode) IsElement() bool {
	return n.DOMNode != nil && n.DOMNode.Type == html.ElementNode
}

// IsText returns true for text nodes.
func (n *LayoutInputNode) IsText() bool {
	return n.DOMNode != nil && n.DOMNode.Type == html.TextNode
}

// TagName returns the element's tag name, or "" for text/anonymous nodes.
func (n *LayoutInputNode) TagName() string {
	if n.DOMNode != nil {
		return n.DOMNode.TagName
	}
	return ""
}

// TextContent returns the text content for text nodes, or "".
func (n *LayoutInputNode) TextContent() string {
	if n.DOMNode != nil {
		return n.DOMNode.Text
	}
	return ""
}

// IsListItem returns true when this node establishes a list item — either
// `display: list-item` (block-level) or `display: inline list-item`
// (inline-level). Mirrors Blink's BlockNode::IsListItem() /
// ComputedStyle::IsDisplayListItem().
func (n *LayoutInputNode) IsListItem() bool {
	return n.style != nil && n.style.IsListItemDisplay()
}

// ListMarkerBlockNodeIfListItem returns the ::marker pseudo-element
// LayoutInputNode for an OUTSIDE marker on a list-item node, or nil otherwise.
//
// Mirrors Blink's BlockNode::ListMarkerBlockNodeIfListItem, which returns the
// LayoutOutsideListMarker so the block layout algorithm can carry it as an
// UnpositionedListMarker and claim it against the content baseline.
//
// Only OUTSIDE markers are returned here: an inside marker flows through the
// inline path as the first in-flow inline item (Phase 3) and is not subject
// to the carry/claim protocol — exactly the LayoutInsideListMarker vs
// LayoutOutsideListMarker split. Returns nil for inside markers and for
// non-list-items.
func (n *LayoutInputNode) ListMarkerBlockNodeIfListItem() *LayoutInputNode {
	if n == nil || n.markerNode == nil {
		return nil
	}
	if !n.markerNode.MarkerIsOutside {
		return nil
	}
	return n.markerNode
}

// MarkerNode returns the ::marker pseudo-element LayoutInputNode for a
// list-item node (inside or outside), or nil. Mirrors Blink
// LayoutListItem::Marker().
func (n *LayoutInputNode) MarkerNode() *LayoutInputNode {
	if n == nil {
		return nil
	}
	return n.markerNode
}

// IsMarkerNode reports whether this node is the synthetic ::marker
// pseudo-element. Used by the ::first-letter walk and inline collection to
// identify and skip the marker box.
func (n *LayoutInputNode) IsMarkerNode() bool {
	return n != nil && n.isMarkerNode
}

// ListMarkerOccupiesWholeLine returns true when list-style-position:inside
// causes the marker to occupy the first line of content (inside marker).
// Mirrors Blink's BlockNode::ListMarkerOccupiesWholeLine().
// Always false for outside markers (the common case).
func (n *LayoutInputNode) ListMarkerOccupiesWholeLine() bool {
	if n.style == nil {
		return false
	}
	return n.style.GetListStylePosition() == "inside"
}

// hasUnsplittableScrollingOverflow reports whether this node is a scroll
// container — overflow scroll/auto/hidden on either axis (clip and visible
// are NOT scroll containers). Any scrollable container is treated as
// monolithic: fragmenting scrollbars is only workable in non-interactive
// media, and louis14 renders screen media only, so Blink's Printing()
// escape hatch is omitted.
//
// Mirrors LayoutBox::HasUnsplittableScrollingOverflow
// (layout_box.cc:3639-3649 @ a9f50e522efa9005e6ec765a9a785c74f5c2c86b).
func (n *LayoutInputNode) hasUnsplittableScrollingOverflow() bool {
	isScrollable := func(o css.OverflowType) bool {
		return o == css.OverflowScroll || o == css.OverflowAuto || o == css.OverflowHidden
	}
	return isScrollable(n.style.GetOverflowX()) || isScrollable(n.style.GetOverflowY())
}

// IsMonolithic reports whether this node must never be fragmented across
// column/page boundaries. A monolithic child is laid out without
// fragmentainer constraints and moved past break points as a unit; if it is
// too tall to fit anywhere it overflows the fragmentainer (multicol) rather
// than being sliced.
//
// Mirrors LayoutBox::IsMonolithic (layout_box.cc:3651-3666 @
// a9f50e522efa9005e6ec765a9a785c74f5c2c86b). The isWritingModeRoot argument
// stands in for Blink's `Parent() && IsWritingModeRoot()` clause:
// LayoutInputNode has no parent pointer (two-tier collapse, see the type
// doc), so the caller supplies the parent-vs-child writing-mode comparison.
//
// Clauses louis14 cannot express yet are omitted (same Blink cite):
// IsInline (callers gate inline children separately, as Blink does at
// fragmentation_utils.cc:336-339), IsSemiReplaced, IsOverscrollContainer,
// fixed-positioned while printing, IsFrameSet, line-clamp, and
// scroll-marker-group.
func (n *LayoutInputNode) IsMonolithic(isWritingModeRoot bool) bool {
	if isWritingModeRoot {
		return true
	}
	if n.style == nil {
		return false
	}
	return n.hasUnsplittableScrollingOverflow() || n.style.ShouldApplySizeContainment()
}
